<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8"/>
        <title>Slim 3</title>
        <link href='//fonts.googleapis.com/css?family=Lato:300' rel='stylesheet' type='text/css'>
        <style>
            body {
                margin: 50px 0 0 0;
                padding: 0;
                width: 100%;
                font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
                text-align: center;
                color: #aaa;
                font-size: 13px;
            }

            h1 {
                color: #719e40;
                letter-spacing: -3px;
                font-family: 'Lato', sans-serif;
                font-size: 100px;
                font-weight: 200;
                margin-bottom: 0;
            }
        </style>
    </head>
    <body>
        <h2>Detalle de Empleado</h2>

        <div class="container col-lg-6">
            <div class="form-group">
                <label for="ID">Nombre</label>
                <input type="text" class="form-control" value="<?php echo $empleado['name']?>">
            </div>
             <div class="form-group">
                <label for="ID">Email</label>
                <input type="text" class="form-control" value="<?php echo $empleado['email']?>">
            </div>
            <div class="form-group">
                <label for="ID">Teléfono</label>
                <input type="text" class="form-control" value="<?php echo $empleado['phone']?>">
            </div>
            <div class="form-group">
                <label for="ID">Dirección</label>
                <input type="text" class="form-control" value="<?php echo $empleado['address']?>">
            </div>
            <div class="form-group">
                <label for="ID">Posición</label>
                <input type="text" class="form-control" value="<?php echo $empleado['position']?>">
            </div>
             <div class="form-group">
                <label for="ID">Salario</label>
                <input type="text" class="form-control" value="<?php echo $empleado['salary']?>">
            </div>
            <div class="form-group">
                <label for="ID">Experiencia</label>
                <input type="text" class="form-control" value="<?php echo $empleado['skills']?>">
            </div>
            <button onclick="goBack()">Regresar</button>
        </div>
    </body>
    <script>
        function goBack() {
            window.history.back();
        }
    </script>
</html>
